version: "3"

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: homework_04
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"